### ISSUE TITLE
panic: interface conversion: image.Image is *image.Paletted, not *image.RGBA

### ISSUE THREAD

**Issue by jiharal** [divan/qrlogo#3]

**Comment by dignifiedquire** [comment]
Same here

**Comment by divan** [comment]
@s1gu @dignifiedquire can you please describe steps to reproduce, I'll take a look at it tomorrow.

**Comment by divan** [comment]
Ah sorry. there is a PR open on this: https://github.com/divan/qrlogo/pull/2

**Comment by divan** [comment]
https://github.com/divan/qrlogo/pull/2 merged, can you please test now?

**Comment by dignifiedquire** [comment]
yes, seems to work now 👍 thank you
